export SECRET_KEY='+&b*7z(%@y4fl@=wy_t31di_f12yoodd&s%jr5rw$_az!-36s4'
export DB_NAME=work_tracker_db
export DB_USER=work_tracker
export DB_PASSWORD=pAssw0rd
export DJANGO_SETTINGS_MODULE=worktogether.local
export EMAIL_HOST=smtp.sendgrid.net
export EMAIL_HOST_PASSWORD=allright45#
export EMAIL_HOST_USER=yogeshk
export EMAIL_PORT=587
export EMAIL_USE_TLS=True
